//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.APIData {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiStateToMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiStateToMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HWeb.APIData.ApiStateToMessage", typeof(ApiStateToMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定成功 的本地化字符串。
        /// </summary>
        internal static string BindDevice_0 {
            get {
                return ResourceManager.GetString("BindDevice_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string BindDevice_1000 {
            get {
                return ResourceManager.GetString("BindDevice_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不存在 的本地化字符串。
        /// </summary>
        internal static string BindDevice_1100 {
            get {
                return ResourceManager.GetString("BindDevice_1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备已被绑定 的本地化字符串。
        /// </summary>
        internal static string BindDevice_1500 {
            get {
                return ResourceManager.GetString("BindDevice_1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备已存在 的本地化字符串。
        /// </summary>
        internal static string BindDevice_1550 {
            get {
                return ResourceManager.GetString("BindDevice_1550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败 的本地化字符串。
        /// </summary>
        internal static string BindDevice_4000 {
            get {
                return ResourceManager.GetString("BindDevice_4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string DeviceCheck_1000 {
            get {
                return ResourceManager.GetString("DeviceCheck_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不存在 的本地化字符串。
        /// </summary>
        internal static string DeviceCheck_1100 {
            get {
                return ResourceManager.GetString("DeviceCheck_1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备属于自己 的本地化字符串。
        /// </summary>
        internal static string DeviceCheck_1105 {
            get {
                return ResourceManager.GetString("DeviceCheck_1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已获得该设备访问权限 的本地化字符串。
        /// </summary>
        internal static string DeviceCheck_1106 {
            get {
                return ResourceManager.GetString("DeviceCheck_1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备已被绑定，请先在设备方解绑 的本地化字符串。
        /// </summary>
        internal static string DeviceCheck_1107 {
            get {
                return ResourceManager.GetString("DeviceCheck_1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string HealthInfo_0 {
            get {
                return ResourceManager.GetString("HealthInfo_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到数据 的本地化字符串。
        /// </summary>
        internal static string HealthInfo_200 {
            get {
                return ResourceManager.GetString("HealthInfo_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string HealthReport_0 {
            get {
                return ResourceManager.GetString("HealthReport_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功，但没有数据 的本地化字符串。
        /// </summary>
        internal static string HealthReport_200 {
            get {
                return ResourceManager.GetString("HealthReport_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string ListDevice_0 {
            get {
                return ResourceManager.GetString("ListDevice_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功，但是没有数据 的本地化字符串。
        /// </summary>
        internal static string ListDevice_100 {
            get {
                return ResourceManager.GetString("ListDevice_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数不正确 的本地化字符串。
        /// </summary>
        internal static string ListDevice_2002 {
            get {
                return ResourceManager.GetString("ListDevice_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备方登陆失败 的本地化字符串。
        /// </summary>
        internal static string Login_1001 {
            get {
                return ResourceManager.GetString("Login_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册成功 的本地化字符串。
        /// </summary>
        internal static string Register_0 {
            get {
                return ResourceManager.GetString("Register_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已被注册 的本地化字符串。
        /// </summary>
        internal static string Register_1001 {
            get {
                return ResourceManager.GetString("Register_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败 的本地化字符串。
        /// </summary>
        internal static string Register_1002 {
            get {
                return ResourceManager.GetString("Register_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名，密码不能为空 的本地化字符串。
        /// </summary>
        internal static string Register_1003 {
            get {
                return ResourceManager.GetString("Register_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备Imei码不存在 的本地化字符串。
        /// </summary>
        internal static string Register_1100 {
            get {
                return ResourceManager.GetString("Register_1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备已被注册 的本地化字符串。
        /// </summary>
        internal static string Register_1102 {
            get {
                return ResourceManager.GetString("Register_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑成功 的本地化字符串。
        /// </summary>
        internal static string RemoveShare_0 {
            get {
                return ResourceManager.GetString("RemoveShare_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑失败 的本地化字符串。
        /// </summary>
        internal static string RemoveShare_1001 {
            get {
                return ResourceManager.GetString("RemoveShare_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        internal static string SendCommand_0 {
            get {
                return ResourceManager.GetString("SendCommand_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不存在 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1101 {
            get {
                return ResourceManager.GetString("SendCommand_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号码未填写 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1108 {
            get {
                return ResourceManager.GetString("SendCommand_1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不在线 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1800 {
            get {
                return ResourceManager.GetString("SendCommand_1800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送超时 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1801 {
            get {
                return ResourceManager.GetString("SendCommand_1801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发失败 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1802 {
            get {
                return ResourceManager.GetString("SendCommand_1802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令已发送 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1803 {
            get {
                return ResourceManager.GetString("SendCommand_1803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24小时短信发送超过30条 的本地化字符串。
        /// </summary>
        internal static string SendCommand_1804 {
            get {
                return ResourceManager.GetString("SendCommand_1804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定中间号码失败 的本地化字符串。
        /// </summary>
        internal static string SendCommand_2003 {
            get {
                return ResourceManager.GetString("SendCommand_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备正在拍照 的本地化字符串。
        /// </summary>
        internal static string SendCommand_5 {
            get {
                return ResourceManager.GetString("SendCommand_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备存储空间已满 的本地化字符串。
        /// </summary>
        internal static string SendCommand_6 {
            get {
                return ResourceManager.GetString("SendCommand_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不在线,指令已存入队列 的本地化字符串。
        /// </summary>
        internal static string SendCommand_7 {
            get {
                return ResourceManager.GetString("SendCommand_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权操作 的本地化字符串。
        /// </summary>
        internal static string SendCommand_7000 {
            get {
                return ResourceManager.GetString("SendCommand_7000", resourceCulture);
            }
        }
    }
}
