//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmdConfig
    {
        public int Id { get; set; }
        public int Model { get; set; }
        public string CmdCode { get; set; }
        public string CmdName { get; set; }
        public string DefaultParam { get; set; }
        public string PutType { get; set; }
        public string PutValue { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsNowSend { get; set; }
    }
}
