//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmdLog
    {
        public int Id { get; set; }
        public string CmdCode { get; set; }
        public string CmdName { get; set; }
        public string Imei { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsSucess { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public string Param { get; set; }
        public string Notice { get; set; }
        public string SendLoginName { get; set; }
    }
}
