//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmdQueue
    {
        public int Id { get; set; }
        public Nullable<int> APIDeviceId { get; set; }
        public int Model { get; set; }
        public string IMEI { get; set; }
        public Nullable<System.DateTime> LastExecTime { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CmdCode { get; set; }
        public string Param { get; set; }
        public string Notice { get; set; }
        public Nullable<int> ExceTime { get; set; }
    }
}
