//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortMenu
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public string MenuCode { get; set; }
        public string Url { get; set; }
        public string Note { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string Icon { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Path { get; set; }
    }
}
