//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDBEntities2 : DbContext
    {
        public WebDBEntities2()
            : base("name=WebDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Img> Imgs { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<SysConfig> SysConfigs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserMenu> UserMenus { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<UserTypeToMenu> UserTypeToMenus { get; set; }
        public virtual DbSet<WebLog> WebLogs { get; set; }
        public virtual DbSet<SortMenu> SortMenus { get; set; }
        public virtual DbSet<DeviceAndUser> DeviceAndUsers { get; set; }
        public virtual DbSet<CmdConfig> CmdConfigs { get; set; }
        public virtual DbSet<CmdLog> CmdLogs { get; set; }
        public virtual DbSet<CmdQueue> CmdQueues { get; set; }
    }
}
