//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWeb.Entity.WebEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLog
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LogLevel { get; set; }
        public string LogName { get; set; }
        public string ClientIp { get; set; }
        public string Method { get; set; }
    }
}
